[package]
name = "pingora-proj"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
env_logger = "0.11.3"
log = "0.4.21"
pingora = { version = "0.1.0", features = ["lb"]}
pingora-core = "0.1.0"
pingora-http = "0.1.0"
pingora-proxy = "0.1.0"
structopt = "0.3.26"
